{% set version = "1.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Tplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Tplyr/Tplyr_{{ version }}.tar.gz
  sha256: db0021678575032fccbbee73b9cbb04cd303def552278dcd6b2f10f66f177f5d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat >=0.2.1
    - r-dplyr >=1.0.0
    - r-forcats >=1.0.0
    - r-lifecycle
    - r-magrittr >=1.5
    - r-purrr >=0.3.3
    - r-rlang >=0.4.6
    - r-stringr >=1.4.0
    - r-tibble >=3.0.1
    - r-tidyr >=1.0.2
    - r-tidyselect >=1.1.0
  run:
    - r-base
    - r-assertthat >=0.2.1
    - r-dplyr >=1.0.0
    - r-forcats >=1.0.0
    - r-lifecycle
    - r-magrittr >=1.5
    - r-purrr >=0.3.3
    - r-rlang >=0.4.6
    - r-stringr >=1.4.0
    - r-tibble >=3.0.1
    - r-tidyr >=1.0.2
    - r-tidyselect >=1.1.0

test:
  commands:
    - $R -e "library('Tplyr')"           # [not win]
    - "\"%R%\" -e \"library('Tplyr')\""  # [win]

about:
  home: https://github.com/atorus-research/Tplyr
  license: MIT
  summary: A traceability focused tool created to simplify the data manipulation necessary to create clinical summaries.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
